### ISSUE TITLE
No rmenu-1 or rmenu_wi_1

### ISSUE THREAD

**Issue by illegitimate-egg** [GoodBoyNeon/dotfiles#1]
Clicking on the arch symbol in the top left is supposed to trigger rmenu_1, but there is no rmenu_1 in this repo

**Comment by GoodBoyNeon** [comment]
Thanks for pointing it out! I'll make a push right after getting everything setup.

**Comment by GoodBoyNeon** [comment]
Fixed. Arch icon now has a menu instead of rmenu_1 script.
